version: "3.8"

services:
  web:
    # docker exec -it web /bin/bash
    build:
      context: ./
      dockerfile: dockerfile
    container_name: web
    volumes:
      - ./:/app
    ports:
      - 5173:5173
      - 4173:4173
    tty: true
